title: 개발자J의 투자지침서
description: 주식투자의 모든 정보를 알려드립니다. 주식시장의 시황/뉴스, 매매동향, 종목분석 등을 제공합니다.

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed # Optional: for compressed CSS output

# Apply default layout to all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
